# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "puma", "~> 6.4"
gem "rack", "~> 3.0"
gem "rack-protection", "~> 3.0"
gem "json", "~> 2.7"
gem "sequel", "~> 5.75"
gem "sqlite3", "~> 2.0"
gem "faraday", "~> 2.8"
gem "dotenv", "~> 2.8"
gem "multi_json", "~> 1.15"
gem "nokogiri", "~> 1.16"
gem "oj", "~> 3.16"

group :development, :test do
  gem "rake", "~> 13.0"
  gem "minitest", "~> 5.22"
end
